dist: trusty
sudo: false

language: node_js
node_js:
  - '12.0'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

after_success:
  - npm run codecov

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
